// Generated by scripts/blog-index.mjs from content/blog. Do not edit.
export const BLOG_INDEX: Record<string, { words: number; minutes: number; toc: { id: string; text: string }[] }> = {
  "static-or-dynamic-website": {
    "words": 401,
    "minutes": 2,
    "toc": [
      {
        "id": "what-static-actually-means",
        "text": "What \"static\" actually means"
      },
      {
        "id": "what-dynamic-adds",
        "text": "What \"dynamic\" adds"
      },
      {
        "id": "a-quick-test",
        "text": "A quick test"
      },
      {
        "id": "the-middle-path-most-businesses-take",
        "text": "The middle path most businesses take"
      },
      {
        "id": "what-it-costs-to-start",
        "text": "What it costs to start"
      }
    ]
  },
  "what-a-whatsapp-bot-can-do": {
    "words": 363,
    "minutes": 2,
    "toc": [
      {
        "id": "what-a-bot-does-well",
        "text": "What a bot does well"
      },
      {
        "id": "what-it-should-hand-to-a-person",
        "text": "What it should hand to a person"
      },
      {
        "id": "what-it-needs-from-you",
        "text": "What it needs from you"
      },
      {
        "id": "the-rules-you-cannot-skip",
        "text": "The rules you cannot skip"
      },
      {
        "id": "where-to-start",
        "text": "Where to start"
      }
    ]
  }
};
