/** Builds lib/blog-index.generated.ts from content/blog/*.mdx: word count, reading time and
 *  the table of contents (every "## " heading). Runs before `next dev` and `next build`, so
 *  nothing reads the file system at runtime (the site runs on Workers).
 *  The heading ids use the same slug() as mdx-components.tsx: keep the two in step. */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../content/blog/', import.meta.url);
const slug = (t) => t.toLowerCase().replace(/[*_`"“”‘’']/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const index = {};
for (const file of readdirSync(dir).filter((f) => f.endsWith('.mdx')).sort()) {
  const src = readFileSync(new URL(file, dir), 'utf8');
  const prose = src.replace(/^(import|export) .*$/gm, '').replace(/<[^>]+>/g, ' ').replace(/[#*|_`>-]/g, ' ');
  const words = prose.split(/\s+/).filter(Boolean).length;
  const toc = [...src.matchAll(/^## (.+)$/gm)].map((m) => {
    const text = m[1].replace(/[*_`]/g, '').trim();
    return { id: slug(text), text };
  });
  index[file.replace(/\.mdx$/, '')] = { words, minutes: Math.max(1, Math.round(words / 220)), toc };
}

writeFileSync(new URL('../lib/blog-index.generated.ts', import.meta.url),
  `// Generated by scripts/blog-index.mjs from content/blog. Do not edit.\n` +
  `export const BLOG_INDEX: Record<string, { words: number; minutes: number; toc: { id: string; text: string }[] }> = ${JSON.stringify(index, null, 2)};\n`);
console.log(`blog index: ${Object.keys(index).length} posts`);
