/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: d5ac5bbd5731ea679356686e54d54c63)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	DB: D1Database;
	NEXT_TAG_CACHE_D1: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	SITE_URL: "https://legitforge.example";
	HASH_SALT: string;
	N8N_LEAD_WEBHOOK_URL: string;
	N8N_SHARED_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("./worker").DOQueueHandler>;
	WORKER_SELF_REFERENCE: Service<typeof import("./worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "DOQueueHandler";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "HASH_SALT" | "N8N_LEAD_WEBHOOK_URL" | "N8N_SHARED_KEY" | "TURNSTILE_SECRET_KEY">> {}
}
