/** Worker entry (PLAN §8.6): OpenNext serves every request; the daily cron prunes the
 *  short-lived tables. R3 adds the /ws/demo/[code] route and the DemoRoom export here.
 *  `next dev` never runs this file — use `npm run preview` to exercise it. */

// @ts-ignore: generated by `opennextjs-cloudflare build`
import { default as handler } from './.open-next/worker.js';
import { doctypeFirst } from './lib/doctype-first';
import { deliverLeadAlerts } from './lib/server/lead-delivery';
import { analyticsCutoff } from './lib/analytics';

export default {
  async fetch(request, env, ctx) {
    // lib/doctype-first.ts: the quirks-mode fix (typed with the DOM Response; at run time it is this one)
    return doctypeFirst(await handler.fetch(request, env, ctx)) as never;
  },

  async scheduled(controller, env, ctx) {
    const now = Date.now();
    ctx.waitUntil(deliverLeadAlerts(env).catch(() => console.error('[lead-alert] scheduled delivery interrupted')));
    if (controller.cron !== '0 3 * * *') return;
    ctx.waitUntil(env.DB.batch([
      env.DB.prepare('DELETE FROM rate_events WHERE at < ?').bind(now - 24 * 3600_000),
      env.DB.prepare('DELETE FROM demo_sessions WHERE created_at < ?').bind(now - 24 * 3600_000),
      env.DB.prepare('DELETE FROM wa_processed WHERE received_at < ?').bind(now - 7 * 24 * 3600_000),
      env.DB.prepare('DELETE FROM lead_receipts WHERE expires_at <= ?').bind(now),
      env.DB.prepare("DELETE FROM admin_sign_ins WHERE at < datetime('now', '-90 days')"),
      env.DB.prepare('DELETE FROM events WHERE at < ?').bind(analyticsCutoff(now)),
    ]));
  },
} satisfies ExportedHandler<CloudflareEnv>;

// @ts-ignore: generated at build time (OpenNext's revalidation queue)
export { DOQueueHandler } from './.open-next/worker.js';
